version: '3.7'

services:

  charging-station-web:
    container_name: charging-station-web
    build:
      context: ./charging-station-web
      dockerfile: Dockerfile
    volumes:
      - './app'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  charging-station-service:
    container_name: charging-station-service
    build:
      context: ./charging-station-service
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development