spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: admin
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver

server:
  port: 8080