version: '3.7'

services:

  sample:
    container_name: charging
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development